/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as rootCalendarIndexRouteImport } from './routes/(root)/calendar/index'

const rootIndexRoute = rootIndexRouteImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const rootCalendarIndexRoute = rootCalendarIndexRouteImport.update({
  id: '/(root)/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof rootIndexRoute
  '/calendar': typeof rootCalendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof rootIndexRoute
  '/calendar': typeof rootCalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root)/': typeof rootIndexRoute
  '/(root)/calendar/': typeof rootCalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar'
  id: '__root__' | '/(root)/' | '/(root)/calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootIndexRoute: typeof rootIndexRoute
  rootCalendarIndexRoute: typeof rootCalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/calendar/': {
      id: '/(root)/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof rootCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  rootIndexRoute: rootIndexRoute,
  rootCalendarIndexRoute: rootCalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
